In [1]:
# some notes when learning course: Introduction to Data Science in Python

In [2]:
# Week 1

In [3]:
import numpy as np
import math

In [11]:
a = np.array([1,2,3])
print(a)
print(a.ndim)
print(a.shape)

[1 2 3]
1
(3,)


In [12]:
b = np.array([[1,2,3],[4,5,6]])
print(b.ndim)
print(b.shape)

2
(2, 3)


In [15]:
ones = np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [17]:
a = np.linspace(10,20,50)
a.shape

(50,)

In [29]:
A = np.array([[0,1],[2,1]])
B = np.array([[3,4],[5,6]])
print(A*B)
print(A@B)
print(np.dot(A,B))

[[ 0  4]
 [10  6]]
[[ 5  6]
 [11 14]]
[[ 5  6]
 [11 14]]


In [36]:
b = np.arange(1,16,1).reshape(3,5)
print(b.sum(axis = 1))

[15 40 65]


In [39]:
from PIL import Image
from IPython.display import display
